### ISSUE TITLE
Program is not working on Linux Ubuntu 20.10

### ISSUE THREAD

**Issue by vcwild** [Thalmonn/cadastrei#3]
### Issue

O programa não está inicializando corretamente no Linux. 

A runtime não consegue ser executada pois não foi possível renderizar o ícone `mainicon.ico` que não foi corretamente identificado como bitmap pelo driver do sistema.

### Mensagem de erro

```sh
Traceback (most recent call last):
  File "source/main.py", line 5, in <module>
    root = janelaprincipal.JanelaPrincipal()
  File "/home/vcwild/Projects/cadastrei/source/modules/janelaprincipal.py", line 22, in __init__
    JanelaPrincipal.iconbitmap(self, path+'/resources/img/icons/mainicon.ico')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2071, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/vcwild/Projects/cadastrei/source/resources/img/icons/mainicon.ico" not defined
```

### Hipóteses

A imagem .ico é um arquivo bitmap. Pela leitura do sistema Linux o arquivo está anotado como tipo Windows icon `vnd.microsoft.icon`

### Reprodutibilidade

Sistema: Linux pop-os 5.8.0-7642-generic #20.10-Ubuntu SMP Wed Feb 3 02:27:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

#### Libs instaladas

```
Package            Version
------------------ -------
altgraph           0.17
cx-Freeze          6.5.3
et-xmlfile         1.0.1
importlib-metadata 3.4.0
jdcal              1.4.1
openpyxl           3.0.6
Pillow             8.1.0
pip                20.1.1
pkg-resources      0.0.0
pygame             2.0.1
setuptools         44.0.0
zipp               3.4.0
```

#### Instruções para reprodução do erro

- Clonado repo
- Instalado runtime python-tk
- Criado ambiente virtual
- Instaladas as bibliotecas do arquivo de requirements
- Exportada variável de ambiente `export DISPLAY=:8; xhost+`
- Executado arquivo `main.py` do pacote **source**

**Comment by Thalmonn** [comment]
Verifiquei as informações e pelo o que percebi o problema esta no formato .ico que é reconhecido como padrão para Windows, o mesmo pode acontecer com os sons em .wav. Durante o procedimento de portabilidade para Linux, irei verificar como adaptar isso. Provavelmente utilizando o Pillow para transformar as imagens em png.

Grato demais pela informação reportada. :heart:
